version: '3'
services:
 spring_app_service:
  container_name: spring-app-container
  image: "maven-project:$BUILD_TAG"
  build:
   context: build
   dockerfile: Dockerfile
  ports: 
   - "8001:8001"

